apiVersion: apps/v1
kind: Deployment
metadata:
  name: circles-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: circles-api
  template:
    metadata:
      labels:
        app: circles-api
    spec:
      automountServiceAccountToken: false
      containers:
      - name: circles-api
        image: europe-southwest1-docker.pkg.dev/circles4dev/circles/circles.api:latest
        ports:
        - containerPort: 5001
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        resources:
          limits:
            memory: "512Mi"
            ephemeral-storage: "100Mi"
          requests:
            memory: "256Mi"
            ephemeral-storage: "10Gi"
          
---
apiVersion: v1
kind: Service
metadata:
  name: circles-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5001
  selector:
    app: circles-api