@circles.api_HostAddress = http://localhost:5130

GET {{circles.api_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{circles.api_HostAddress}}/api/v1/circles?denomination=2
Accept: application/json

###
