steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'europe-southwest1-docker.pkg.dev/circles4dev/circles/circles.web:latest'
      - '-f'
      - '.docker/Docker.client'
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'europe-southwest1-docker.pkg.dev/circles4dev/circles/circles.web:latest'
images:
  - 'europe-southwest1-docker.pkg.dev/circles4dev/circles/circles.web:latest'
